export const shopCategories = [
  { value: "fashion", label: "Fashion & Clothing" },
  { value: "shoes", label: "Shoes & Footwear" },
  { value: "bags", label: "Bags & Luggage" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "watches", label: "Watches" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "health", label: "Health & Wellness" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "phones", label: "Phones & Accessories" },
  { value: "computers", label: "Computers & Laptops" },
  { value: "gaming", label: "Gaming" },
  { value: "home", label: "Home & Living" },
  { value: "furniture", label: "Furniture" },
  { value: "kitchen", label: "Kitchen & Dining" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "groceries", label: "Groceries & Food" },
  { value: "beverages", label: "Beverages" },
  { value: "baby", label: "Baby & Kids" },
  { value: "toys", label: "Toys & Hobbies" },
  { value: "books", label: "Books & Stationery" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "automotive", label: "Automotive & Accessories" },
  { value: "tools", label: "Tools & Hardware" },
  { value: "pets", label: "Pet Supplies" },
  { value: "art", label: "Art & Collectibles" },
  { value: "music", label: "Music & Instruments" },
  { value: "cameras", label: "Cameras & Photography" },
  { value: "office", label: "Office Supplies" },
  { value: "industrial", label: "Industrial & Scientific" },
  { value: "handmade", label: "Handmade & Crafts" },
  { value: "digital", label: "Digital Products" },
  { value: "services", label: "Services" },
  { value: "other", label: "Other" },
];
